### ISSUE TITLE
Remove /usr/lib from makevars for portability

### ISSUE THREAD

**Issue by theAeon** [kharchenkolab/sccore#12]
Hi all-I was installing a source-compiled version of this package on our cluster and was running into link issues with the default setting. /usr/lib on many systems is designated for 32 bit multilib support while lib64 is the correct system linking directory. Usually, for the sake of portability, its best to leave the default library path detection to the compiler rather than hardcoding it.

Appreciate it!

**Comment by evanbiederstedt** [comment]
> /usr/lib on many systems is designated for 32 bit multilib support while lib64 is the correct system linking directory.

Interesting! I didn't know this

Alright, I'll remove on all R packages here and update on CRAN. Thanks @theAeon

**Comment by theAeon** [comment]
no worries! if you want to hold off on the cran submission (for leidenAlg, at least) I'm trying to convince it to link to the already-existing rigraph library instead of building it again.

**Comment by evanbiederstedt** [comment]
@theAeon Thanks, please keep me updated. I think I have six packages on CRAN whereby I did this (for reasons of mental laziness...I just never heard of issues before). So I'm happy to change them all.

**Comment by evanbiederstedt** [comment]
Fixed in Version 1.0.5, on CRAN
