### ISSUE TITLE
error: a space is required between consecutive right angle brackets (use '> >')

### ISSUE THREAD

**Issue by raquelgarza** [kharchenkolab/sccore#7]
Hello, 

I ran into this error while trying to install sccore. I tried both `devtools::install_github('kharchenkolab/sccore')` and `install.packages('sccore')`, same issue.

I'm running:
```
R 4.0.2
gcc 10.2.0
clang 12.0.0
```
in MacOS Catalina 10.15.7

The complete error message (I skipped the warnings): 
```
RcppExports.cpp:34:67: error: a space is required between consecutive right angle brackets (use '> >')
Rcpp::List get_nearest_neighbors(const std::vector<std::vector<int>>& adjacency_list, const std::vector<std::vector<double>>& transition_probabilities, int n_verts, int n_cores, double min_prob, int min_visited_verts, double min_prob_lower, int max_hitting_nn_num, int max_commute_nn_num, bool verbose);
                                                                  ^~
                                                                  > >
RcppExports.cpp:34:123: error: a space is required between consecutive right angle brackets (use '> >')
Rcpp::List get_nearest_neighbors(const std::vector<std::vector<int>>& adjacency_list, const std::vector<std::vector<double>>& transition_probabilities, int n_verts, int n_cores, double min_prob, int min_visited_verts, double min_prob_lower, int max_hitting_nn_num, int max_commute_nn_num, bool verbose);
                                                                                                                          ^~
                                                                                                                          > >
RcppExports.cpp:39:69: error: a space is required between consecutive right angle brackets (use '> >')
    Rcpp::traits::input_parameter< const std::vector<std::vector<int>>& >::type adjacency_list(adjacency_listSEXP);
                                                                    ^~
                                                                    > >
RcppExports.cpp:40:72: error: a space is required between consecutive right angle brackets (use '> >')
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type transition_probabilities(transition_probabilitiesSEXP);
                                                                       ^~
                                                                       > >
17 warnings and 4 errors generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘sccore’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sccore’
Error: Failed to install 'sccore' from GitHub:
  (converted from warning) installation of package ‘/var/folders/tg/5bfchk5n1sj8mw9r3m32q11c0000gp/T//RtmpekfKFL/filef4b95bbcc151/sccore_0.1.1.tar.gz’ had non-zero exit status
```

**Comment by evanbiederstedt** [comment]
This is a pre-C++11 compiler giving this error. 

I'm in the process of fixing a few issues for CRAN---this should be fixed shortly, I believe.

**Comment by evanbiederstedt** [comment]
Also, until the CRAN issues are fixed, you may want to check out how to install packages on Mac OS here: https://github.com/kharchenkolab/conos/wiki/Installing-Conos-for-Mac-OS

Same applies to sccore.

**Comment by evanbiederstedt** [comment]
Hi @ra7555ga-s 

With sccore version 0.1.1 on CRAN, I think this is now resolved.

**Comment by JacobRPrice** [comment]
Hi @evanbiederstedt , I'm running into similar errors when trying to update the `Rcpp` package (I came across this issue through a google search). If you don't mind me asking, is this type of error due to something in a specific R package's code, or incompatibilities with the compiler itself? I'm asking because `Rcpp` seemed to install just fine and now the update is what is giving me trouble.

**Comment by evanbiederstedt** [comment]
Hi @JacobRPrice 

Yeah, the error shown is something that C++98 used to throw. After C++11, there was no problem. 

The compilation error is the following:

```
std::vector<std::vector<int>>
```

Before C++11, that would throw an error. 

I could do two things (later):
(1) put `SystemRequirements: C++11` in the DESCRIPTION file to make this clear
(2)  put spaces here so users don't run into this issue

So, I'd update your compiler. You can see the CRAN binaries compile/install correctly here: https://cran.r-project.org/web/checks/check_results_sccore.html

I'll update the package with the above at some point. 

Thanks, Evan

**Comment by JacobRPrice** [comment]
Hi Evan, thank-you for the explanation! It looks like Rcpp is also passing [its checks](https://cran.r-project.org/web/checks/check_results_Rcpp.html). I'll have to look into how to update my compiler, as both of my work machines are Macs and my understanding is that the c++ compilers that Apple uses are sub-par/not optimal for working with R.

**Comment by evanbiederstedt** [comment]
Hi @JacobRPrice 

Actually, the DESCRIPTION already includes `SystemRequirements: C++11`

RE: Rcpp and C++11, this looks relevant: https://gallery.rcpp.org/articles/first-steps-with-C++11/
